/* eslint-disable no-unused-vars */
export enum LoginActionType {
  LOGIN_USER = 'LOGIN_USER',
  REGISTER_USER = 'REGISTER_USER',
  CLEAR_REDUCER = 'CLEAR_REDUCER',
  CLEAR_REGISTER = 'CLEAR_REGISTER',
  UPDATE_LOGIN = 'UPDATE_LOGIN',
}

export enum DashboardActionType {
  SLIDER_API = 'SLIDER_API',
  MENU_API = 'MENU_API',
  REFER_AND_EARN = 'REFER_AND_EARN',
  CHANGE_PASSWORD = 'CHANGE_PASSWORD',
  CLEAR_CHANGE_PASSWORD = 'CLEAR_CHANGE_PASSWORD',
}

export enum ProfileActionType {
  MY_PROFILE = 'MY_PROFILE',
  GET_STATES = 'GET_STATES',
  GET_CITY = 'GET_CITY',
  UPDATE_PROFILE = 'UPDATE_PROFILE',
}
